### PR TITLE
Rewrite npm's scripts in JavaScript

### LINKED ISSUE #183: Fails to install on Windows npm, pnpm, or yarn
The postinstall script [uses `sh`](https://github.com/evilmartians/lefthook/blob/master/.npm/bin/lefthook) which is not available in Windows by default. The code itself is pretty simple. Could you rewrite it in JavaScript itself? There is no need to depend on sh for such a simple script.

```js
❯ pnpm i --save-dev @arkweid/lefthook
Packages: +1 -141
+--------------------------------------------------------------------------------------------------------------------------------
node_modules/.pnpm/@arkweid+lefthook@0.7.4/node_modules/@arkweid/lefthook: Running postinstall script, failed in 69ms
.../node_modules/@arkweid/lefthook postinstall$ node postinstall.js
│ node:events:342
│       throw er; // Unhandled 'error' event
│       ^
│ Error: spawn C:\Users\aminy\node_modules\.pnpm\@arkweid+lefthook@0.7.4\node_modules\@arkweid\lefth
│     at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
│     at onErrorNT (node:internal/child_process:480:16)
│     at processTicksAndRejections (node:internal/process/task_queues:83:21)
│ Emitted 'error' event on ChildProcess instance at:
│     at Process.ChildProcess._handle.onexit (node:internal/child_process:288:12)
│     at onErrorNT (node:internal/child_process:480:16)
│     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
│   errno: -4058,
│   code: 'ENOENT',
│   syscall: 'spawn C:\\Users\\aminy\\node_modules\\.pnpm\\@arkweid+lefthook@0.7.4\\node_modules
│   path: 'C:\\Users\\aminy\\node_modules\\.pnpm\\@arkweid+lefthook@0.7.4\\node_modules\\@arkwei
│   spawnargs: [ 'install', '-f' ]
│ }
└─ Failed in 69ms
 ERROR  Command failed with exit code 1.
Progress: resolved 22, reused 22, downloaded 0, added 0
```

The `postinstall` script itself is very simple. Not sure why `pnpm` fails to run it.

This the npmrc that I used in most of my projects:
```
public-hoist-pattern[]=*
package-lock=false
lockfile=true
prefer-frozen-lockfile=false
```

### PR DESCRIPTION
**Pull request by aminya**
- This removes the dependency on `sh` for a Node env, which is not available on Windows. 
- It also speeds up the startup time because there is no `sh` script anymore to slow things down. Nodejs itself spawns the executable directly.

Fixes #183 
Related to #16

### CODE REVIEW

**Comment by aminya** [comment]
@DmitryTsepelev Could you take a look at this? It makes it possible to use lefthook on Windows.

**Comment by aminya** [comment]
You're welcome. I am **also** contributing in my free time from my commercial work, and since the mentioned member approved two pull requests today, I added a kindly reminder. In the meantime, I am using my local fork, and I am not in rush at all.

**Review by skryukov — APPROVED** [review]

**Comment by Envek** [comment]
Windows support is especially hard to do right as we don't have anyone who is on Windows. That's why your contribution is especially valuable. @aminya, thank you very much!

**Comment by Envek** [comment]
Released in [0.7.5](https://github.com/evilmartians/lefthook/releases/tag/v0.7.5). Thank you!

**Comment by aminya** [comment]
You're welcome!

**Comment by PikachuEXE** [comment]
This change (precisely the removal of `.npm/bin/lefthook`) causes #232.
Would be good to hear your opinion on how to fix #232. (Probably better to discuss there)

**Pull request merged**
