### PR TITLE
feat: add python package

### PR DESCRIPTION
**Pull request by mrexox**
Closes https://github.com/evilmartians/lefthook/issues/119

**:zap: Summary**

- [x] Add Python wrapper for lefthook binaries
- [x] Adjust the CI to deploy the package

### CODE REVIEW

**Comment by mrexox** [comment]
@orsinium , is it possible for you to transfer the [lefthook](https://pypi.org/project/lefthook/) project to my [profile](https://pypi.org/user/mrexox/) or add me as an admin? `lefthook` is a really good name :) I wish I could officially maintain it just like NPM or Rubygems packages.

**Comment by orsinium** [comment]
Done. Also, I see that @hyperupcall already was the owner of the package.

**Comment by mrexox** [comment]
Thank you!

**Comment by hyperupcall** [comment]
Yup I wanted to package it but did not get around to doing it. Glad to see this done!

**Pull request merged**
