### PR TITLE
Add .lefthookrc loading

### LINKED ISSUE #178: `npm: not found` when using a git client and nvm
Since `v0.7.3` it appears Lefthook is struggling to find npm when using a git client (e.g. GitHub Desktop/SmartGit) while using `nvm`. 

_It works as expected when making a commit directly from the command line ~~or when using `v0.7.2`~~._

OS: Ubuntu

## Error
```bash
Commit failed - exit code 1 received, with output: 
Lefthook v0.7.3
RUNNING HOOKS GROUP: pre-commit
⠋ waiting 
1_stylelint (SKIP. NO FILES FOR INSPECTION)
  EXECUTE > 2_eslint
 sh: 1: npm: not found
 3_prettier (SKIP BY BROKEN PIPE)
SUMMARY: (done in 0.01 seconds)
🥊  2_eslint
```

## `lefthook.yml`
```yml
pre-commit:
  piped: true
  commands:
    1_stylelint:
      tags: frontend linting styles
      glob: "*.{scss,vue}"
      run: npm exec -- stylelint {staged_files} --quiet --fix
    2_eslint:
      tags: frontend linting javascript
      glob: "*.{js,vue}"
      run: "npm exec -- eslint {staged_files} --quiet --fix"
    3_prettier:
      tags: frontend formatting styles javascript
      glob: "*.{scss,css,js,vue}"
      run: "npm exec -- prettier --check {staged_files} --write --ignore-unknown"
```

## NPM

We are currently using `nvm` to manage our `npm` installation.

```
❯ which npm
/home/lee/.nvm/versions/node/v15.14.0/bin/npm
```

If we use the standard `npm` package (`sudo apt install nodejs npm`) it works fine.

```
❯ which npm
/usr/bin/npm
```

### PR DESCRIPTION
**Pull request by skryukov**
Fixes #178 
Probably fixes also #99

The same workaround used in Husky https://typicode.github.io/husky/#/?id=command-not-found

### CODE REVIEW

**Comment by Envek** [comment]
Why we need one more config file? Why we can't just add some key to [`lefthook-local.yml`](https://github.com/evilmartians/lefthook#local-config) for example?

**Comment by SAGARSURI** [comment]
Any update on this?

**Comment by skryukov** [comment]
So the problem is - we need to load `PATH` using shell script only (in the case of npm-based Lefthook installation). Parsing a full-featured yaml file is overkill. We can `grep` file to find line by key name, but what if it will be multiline value? In that case, `.lefthookrc` seemed like a good enough solution.

@Envek wdyt?

**Comment by Envek** [comment]
In #178 lefthook itself is being found correctly, parses Lefthook YAML config and fails to execute commands defined there due to the incomplete PATH set by GUI clients. So there is no need to execute anything in the hook file before invoking Lefthook itself.

**Comment by skryukov** [comment]
@Envek in #178 Lefhook installed as a local dependency via npm, so I think it is found by this line https://github.com/evilmartians/lefthook/blob/master/cmd/templates/hook.tmpl#L20

But `npx lefthook`, `yarn lefthook`, and even `bundle exec lefthook` won't work as far as I understand.

**Comment by lm93547** [comment]
Any update on this

**Comment by JosephNK** [comment]
this update need

**Comment by Krunal-K-SimformSolutions** [comment]
Any update? how much time does it take to merge this PR because I have the same issue?

**Pull request closed without merging**
