### PR TITLE
perf(`npm`): startup time reduce

### LINKED ISSUE #703: Performance for `npm` could be even more faster?
### :zap: Summary

Hi @evilmartians team/contributors

Tuning `npm` package could lead into performance improvements and reducing startup execution.

Opened similar PR/Issue on other projects but impossible to check locally due of hard running local or lacking of running locally easier script.

- https://github.com/dprint/dprint/pull/839/files & https://github.com/dprint/dprint/pull/840/files
- https://github.com/biomejs/biome/pull/2359/files
- https://github.com/oxc-project/oxc/pull/2920/files

As these PR not merged into neither of them, so first decided to ask from you

### Value

| Command                     |   Mean [ms] | Min [ms] | Max [ms] |    Relative |
| :-------------------------- | ----------: | -------: | -------: | ----------: |
| `../lint-staged.sh`         | 154.3 ± 2.8 |    151.1 |    159.3 |        1.00 |
| `lint-staged`               | 306.9 ± 6.1 |    300.3 |    320.8 | 1.99 ± 0.05 |
| `lefthook run pre-commit`   | 202.8 ± 4.4 |    197.3 |    210.1 | 1.31 ± 0.04 |
| `./lefthook run pre-commit` | 162.7 ± 3.2 |    160.4 |    170.7 | 1.05 ± 0.03 |

### Behavior and configuration changes

If `npx` is not important, can be tuned for using `lefthook` binary from `optionalDependencies` or prepare script can download and change binary for main `npm` package `bin` field.

### Test script locally for you

<details>
<summary><code>postinstall.js</code></summary>

```js
import { prepare, maps } from "binary2npm";

maps.os = {
  linux: "Linux",
  freebsd: "Freebsd",
  darwin: "MacOS",
  win32: "Windows",
};
maps.arch = {
  arm64: "arm64",
  x64: "x86_64",
  x86: "x86_64",
};

await prepare({
  remote: "github",
  author: "evilmartians",
  repository: "lefthook",
  remoteToken: process.env.GITHUB_TOKEN,
  binary: "lefthook",
  orders: ["binary", "version", "os", "arch"],
});

```
</details>

- Try run `node postinstall.js`
- Then benchmark direct running versus using custom `bin.js` from `npm` package

### PR DESCRIPTION
**Pull request by dalisoft**
Closes #703 

#### :zap: Summary

This PR should improve startup performance to get even more out of your performant library

#### :ballot_box_with_check: Checklist

- [ ] Check locally
- [ ] Add tests
- [ ] Add documentation

### CODE REVIEW

**Comment by dalisoft** [comment]
Make test i'm getting these results

```sh
❯ make test
go test -cpu 24 -race -count=1 -timeout=30s ./...
?       github.com/evilmartians/lefthook        [no test files]
?       github.com/evilmartians/lefthook/cmd    [no test files]
ok      github.com/evilmartians/lefthook/internal/config        1.318s
ok      github.com/evilmartians/lefthook/internal/git   1.504s
?       github.com/evilmartians/lefthook/internal/lefthook/runner/exec  [no test files]
?       github.com/evilmartians/lefthook/internal/templates     [no test files]
?       github.com/evilmartians/lefthook/internal/system        [no test files]
?       github.com/evilmartians/lefthook/internal/version       [no test files]
ok      github.com/evilmartians/lefthook/internal/lefthook      1.737s
ok      github.com/evilmartians/lefthook/internal/lefthook/runner       1.287s
ok      github.com/evilmartians/lefthook/internal/lefthook/runner/filters       1.730s
ok      github.com/evilmartians/lefthook/internal/log   1.483s
lefthook on  perf-cli-improvement [?] via 🐹 v1.22.2 took 11s 
❯ 
```

It is okay to check `check locally?`

**Comment by dalisoft** [comment]
Testing locally currently isn't possible because of locally it's failed. `make prepare` got these results on macOS

```sh
lefthook/packaging on  perf-cli-improvement [?] 
❯ make prepare
find npm/ -name 'README.md' -exec rm \{} \;
find npm/ -type f -name 'lefthook*' -exec rm \{} \;
git clean -fdX npm-installer/ npm-bundled/ npm-bundled/bin/
Removing npm-bundled/node_modules/
Removing npm-installer/node_modules/
git clean -fdX rubygems/libexec/ rubygems/pkg/
find npm -name 'package.json' -type f -print0 | xargs -0 sed -E -i "s/\"version\": \".+\"/\"version\": \"1.6.10\"/"
sed: 1: "npm/lefthook-linux-x64/ ...": extra characters at the end of n command
make: *** [set-version] Error 1
lefthook/packaging on  perf-cli-improvement [?] 
❯ 
```

**Comment by mrexox** [comment]
There is no need to do this for npm-bundled and npm-installer packages because the binaries from these packages are executed directly in a git hook (with full paths).

So, only `lefthook` package which uses optionalDependencies is the target for this optimization.

**Comment by dalisoft** [comment]
@mrexox I'm tried to optimize all of `npm` packages so any of type `npm` packages uses this performance boost

**Comment by dalisoft** [comment]
@mrexox I am updated PR and now changes affects only `lefthook` package

**Comment by mrexox** [comment]
I understand, but this optimization would work only if you run `npx @evilmartians/lefthook run` which is usually not the way lefthook is being used. Usually it gets executed implicitly from a git hook

**Comment by mrexox** [comment]
Thank you! I will test the PR later this week :+1:

**Comment by dalisoft** [comment]
Thank you too for your time and looking into this PR

**Pull request merged**
