### PR TITLE
Pass all arguments to downstream hooks

### LINKED ISSUE #230: Regression. Lefthook won't pass extra arguments to hooks
In particular, affects [`prepare-commit-msg`](https://git-scm.com/docs/githooks#_prepare_commit_msg) as it takes one to three arguments.

Breaking commit: https://github.com/evilmartians/lefthook/commit/be0bf50605c118f312a6216067691953e8c02cb5#diff-8e2b47f6c23a892f2967380c2b5d2ec57b434885ead6b4995bb6cb9c69695c74L73

Before the commit, full argument list would be passed to a hook

    cmd="lefthook run prepare-commit-msg $@"

after the commit, lefthook would pass first argument only

    eval lefthook $1

### PR DESCRIPTION
**Pull request by pablobirukov**
Fixes #230

### CODE REVIEW

**Review by skryukov — APPROVED** [review]
Hey, @pablobirukov, thanks for the issue and the RP!

**Comment by Envek** [comment]
Thanks! We will release it a few days later.

**Comment by pablobirukov** [comment]
Thanks you @skryukov @Envek.

Any estimates for release?

**Comment by Envek** [comment]
Released in [0.7.7](https://github.com/evilmartians/lefthook/releases/tag/v0.7.7)

**Pull request merged**
